name: Reuse Deployment

on:
    workflow_call:
        secrets:
            test:
                required: true
            MONGO_PASSWORD:
                required: true
        inputs:
          mongodb-uri:
            required: true
            type: string
jobs:
    reuse-deploy:
      runs-on: ubuntu-latest
      environment:
        name: development
        url: https://
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install kubectl CLI
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.26.0'

        - name: Test
          run: echo ${{inputs.mongodb-uri}}    
        
        - name: Fetch Kubernetes Cluster Details
          run: |
            #kubectl version --short
            echo -------------------------------------------
            #kubectl get nodes      