name: Solar System Workflow Lab

on:
    push:

jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Setup NodeJS Version - 18
              uses: actions/setup-node@v3
              with:
                 node-version: 18
            
            - name: Cache NPM dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}      

            - name: Install Dependencies
              run: npm install
              
            - name: Unit testing
              id: nodejs-unit-testing-step
              run: npm test
  
            - name: Archive Test Result
              if: always()
              uses: actions/upload-artifact@v3
              with:
                name: Mocha-Test-Result
                path: test-results.xml
  


